theme: jekyll-theme-cayman
title: Kueue Console
description: Web interface for interacting with and managing Kubernetes Kueue workloads.

# This plugin automatically adds SEO meta tags (including Google Search Console verification)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Replace this with the verification ID Google Search Console gives you
webmaster_verifications:
  google: r-yTwtGYO1P-ss-jGtinRS0tI4Txg5ulKorwtW2Wx-U

# Tell Jekyll that this site lives in a subdirectory
baseurl: "/kueue-console"

# Your site's domain, required for sitemap absolute URLs
url: "https://rnravu.github.io"
